version: "3.3"

services:
    escape:
        build:
            context: .
            dockerfile: Dockerfile

        ports:
            - "8083:80"

        volumes:
            - .:/var/www/html/app